AWSTemplateFormatVersion: '2010-09-09'
Resources:
  FISExperimentTemplate:
    Type: 'AWS::FIS::ExperimentTemplate'
    Properties:
      RoleArn: 'arn:aws:iam::247018008381:role/fisrole' # Replace with your IAM role ARN
      Targets:
        EC2InstanceTarget:
          ResourceType: 'aws:ec2:instance'
          SelectionMode: 'ALL'
          ResourceArns:
            - 'arn:aws:ec2:ap-southeast-2:247018008381:instance/i-0b6587a9b1483779c'  # Replace with your EC2 instance ARN
      Actions:
        StopInstanceAction:
          ActionId: 'aws:ec2:stopInstances'
          Parameters:
            instanceIds: ['i-0b6587a9b1483779c']  # Replace with your EC2 instance ID
          Targets:
            - EC2InstanceTarget
      StopConditions:
        - Type: 'duration'
          DurationSeconds: 60  # Duration for the fault injection experiment