name: FIS Experiment Trigger for NPD

on:
  workflow_dispatch:
    inputs:
      namespace:
        description: "Enter the namespace for the npd environment (e.g., t2, t4, t5)"
        required: true
      fis_experiment:
        description: "Select the FIS experiment template (e.g., ec2_stop.json)"
        required: true

env:
  AWS_REGION: ap-southeast-2
  AWS_ACCOUNT_ID: "YOUR_ACCOUNT_ID"
  AWS_TRUST_ROLE: "YOUR_TRUST_ROLE"
  AWS_DEPLOYMENT_ROLE: "YOUR_DEPLOYMENT_ROLE"

permissions:
  contents: write
  id-token: write

jobs:
  trigger-fis:
    name: Trigger FIS Experiment in NPD
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Namespace
        run: echo "NAMESPACE=${{ github.event.inputs.namespace }}" >> $GITHUB_ENV

      - name: Configure AWS credentials (AssumeRoleWithWebIdentity)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: "${{ env.AWS_TRUST_ROLE }}"
          role-session-name: "GitHubActions"
          aws-region: "${{ env.AWS_REGION }}"

      - name: Configure AWS credentials (AssumeRole)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: "${{ env.AWS_DEPLOYMENT_ROLE }}"
          role-session-name: "GitHubActions"
          aws-region: "${{ env.AWS_REGION }}"
          role-chaining: true

      - name: Trigger FIS Experiment
        run: |
          echo "Triggering FIS experiment for namespace ${{ env.NAMESPACE }}"
          aws fis start-experiment \
            --experiment-template-id ${{ github.event.inputs.fis_experiment }}
