AWSTemplateFormatVersion: '2010-09-09'
Resources:
  FISExperimentTemplate:
    Type: 'AWS::FIS::ExperimentTemplate'
    Properties:
      RoleArn: 'arn:aws:iam::247018008381:role/fisrole'  # Replace with your IAM role ARN
      Targets:
        EC2InstanceTarget: "arn:aws:ec2:ap-southeast-2:247018008381:instance/i-0b6587a9b1483779c"  # Replace with your EC2 instance ARN
      Actions:
        StopInstanceAction:
          ActionId: 'aws:ec2:stopInstances'
          Parameters:
            instanceIds: "i-0b6587a9b1483779c"  # Comma-separated list if you have more than one instance
          Targets:
            EC2InstanceTarget: "arn:aws:ec2:ap-southeast-2:247018008381:instance/i-0b6587a9b1483779c" # Replace with your EC2 instance ARN
      StopConditions:
        - Type: "duration"  # Correct field for stop condition type
          DurationSeconds: 60  # Duration in seconds for the experiment to run
