AWSTemplateFormatVersion: '2010-09-09'
Resources:
  FISExperimentTemplate:
    Type: 'AWS::FIS::ExperimentTemplate'
    Properties:
      Description: FIS-STOP-Instance
      RoleArn: 'arn:aws:iam::247018008381:role/fisrole'  # Replace with your IAM role ARN
      Targets:
        EC2Instance:
          ResourceType: aws:ec2:instance
          ResourceTags:
            Experiment: ChaosReady
          SelectionMode: ALL
      Actions:
        FISStopInstanceAction:
          ActionId: aws:ec2:stop-instances
          Parameters:
            startInstancesAfterDuration: PT3M
          Targets:
            Instance: EC2Instance
      StopConditions:
        - Source: none  # Correct field for stop condition type