name: My first workflow
on: push
jobs:
    first-job:
        runs-on: ubuntu-latest
        steps:
            
            - name: Checkout the own repo
              uses: actions/checkout@v4

            - name: Executing different cmds
              run: |
                echo "Multiple cmds"  
                pwd
                ls -ltra
                cat README.md

            # - name: List the files in the current directory
            #   run: ls -l /

            # - name: Read file
            #   run: cat README.md
            #