AWSTemplateFormatVersion: '2010-09-09'
Resources:
  FISExperimentTemplate:
    Type: 'AWS::FIS::ExperimentTemplate'
    Properties:
      ExperimentTemplateName: 'MyFISExperimentTemplate'
      RoleArn: 'arn:aws:iam::123456789012:role/fis-experiment-role' # Replace with your IAM role ARN
      Targets:
        EC2InstanceTarget:
          ResourceType: 'aws:ec2:instance'
          SelectionMode: 'ALL'
          ResourceArns:
            - 'arn:aws:ec2:us-west-2:123456789012:instance/i-1234567890abcdef0'  # Replace with your EC2 instance ARN
      Actions:
        StopInstanceAction:
          ActionId: 'aws:ec2:stopInstances'
          Parameters:
            instanceIds: ['i-1234567890abcdef0']  # Replace with your EC2 instance ID
          Targets:
            - EC2InstanceTarget
      StopConditions:
        - Type: 'duration'
          DurationSeconds: 60  # Duration for the fault injection experiment
