name: AWS FIS
run-name: AWS FIS

on: push

jobs:
  deploy-fis:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Set up AWS credentials using GitHub Secrets
      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2  # Replace with your AWS region

      # Step 3: Assume the role you created for FIS
      - name: Assume FIS role
        run: |
          ROLE_ARN="arn:aws:iam::247018008381:role/fisrole"  # Replace with your FIS role ARN
          CREDS=$(aws sts assume-role --role-arn $ROLE_ARN --role-session-name "GitHubActionsSession")
          export AWS_ACCESS_KEY_ID=$(echo $CREDS | jq -r '.Credentials.AccessKeyId')
          export AWS_SECRET_ACCESS_KEY=$(echo $CREDS | jq -r '.Credentials.SecretAccessKey')
          export AWS_SESSION_TOKEN=$(echo $CREDS | jq -r '.Credentials.SessionToken')

      # Step 4: Print AWS CLI version
      - name: Print AWS CLI version
        run: |
          aws --version

      # Step 5: Create CloudFormation Stack to deploy FIS experiment template
      - name: Deploy CloudFormation stack
        run: |
          aws cloudformation deploy \
            --template-file fis-template.yml \
            --stack-name fis-experiment-stack \
            --capabilities CAPABILITY_NAMED_IAM

      # Step 6: Verify CloudFormation Stack creation
      - name: Verify CloudFormation stack creation
        run: |
          aws cloudformation describe-stacks --stack-name fis-experiment-stack
