name: Generate ASCII
on: push
jobs:
    ascii-job:
        runs-on : ubuntu-latest
        steps:
          
            - name: Checkout to self repo
              uses: actions/checkout@v4

            - name: Execute shell script using file
              run: ./ascii-script.sh
                
            - name: List all files in repo
              run: ls -ltra