name: Minikube and Helm Example
run-name: Minikube and Helm Workflow

on: push

jobs:
  minikube-helm:
    runs-on: ubuntu-latest
    env:
      APP_NAME: "myapp"
      K8S_NAMESPACE: "default"

    steps:
      - name: Set up Minikube
        run: |
          curl -Lo minikube https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
          chmod +x minikube
          sudo mv minikube /usr/local/bin/
          minikube start --driver=docker
        shell: bash

      - name: Set up kubectl
        run: |
          curl -LO "https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x kubectl
          sudo mv kubectl /usr/local/bin/
          kubectl version --client
        shell: bash
      - name: Set up Helm
        run: |
          curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
          helm version
        shell: bash

      - name: Deploy a simple Helm chart
        run: |
          helm repo add bitnami https://charts.bitnami.com/bitnami
          helm install ${APP_NAME} bitnami/nginx --namespace ${K8S_NAMESPACE}
        shell: bash

      # - name: Create sample ingress
      #   run: |
      #     cat <<EOF | kubectl apply -f -
      #     apiVersion: networking.k8s.io/v1
      #     kind: Ingress
      #     metadata:
      #       name: ${APP_NAME}-ui-alb
      #       namespace: ${K8S_NAMESPACE}
      #       labels:
      #         release: ${APP_NAME}
      #       annotations:
      #         nginx.ingress.kubernetes.io/rewrite-target: /
      #       finalizers:
      #       - kubernetes
      #     spec:
      #       rules:
      #       - host: example.com
      #         http:
      #           paths:
      #           - path: /
      #             pathType: Prefix
      #             backend:
      #               service:
      #                 name: ${APP_NAME}
      #                 port:
      #                   number: 80
      #     EOF
      #   shell: bash
      #     cat <<EOF | kubectl apply -f -
      #     apiVersion: networking.k8s.io/v1
      #     kind: Ingress
      #     metadata:
      #       name: ${APP_NAME}-gateway-alb
      #       namespace: ${K8S_NAMESPACE}
      #       labels:
      #         release: ${APP_NAME}
      #       annotations:
      #         nginx.ingress.kubernetes.io/rewrite-target: /
      #       finalizers:
      #       - kubernetes
      #     spec:
      #       rules:
      #       - host: example.com
      #         http:
      #           paths:
      #           - path: /
      #             pathType: Prefix
      #             backend:
      #               service:
      #                 name: ${APP_NAME}
      #                 port:
      #                   number: 80
      #     EOF
      #   shell: bash

      - name: Get existing release information
        run: |
          kubectl get all -l release=${APP_NAME} --namespace ${K8S_NAMESPACE}
        shell: bash

      - name: Check helm release status
        id: check_release_status
        run: |
          if helm status ${APP_NAME} --namespace ${K8S_NAMESPACE}; then
            echo "release_exists=true" >> $GITHUB_ENV
            echo "Helm release exists"
          else
            echo "release_exists=false" >> $GITHUB_ENV
            echo "Helm release does not exist"
          fi
        shell: bash
        continue-on-error: true

      - name: Check ui ingress exists
        id: check_ui_ingress
        run: |
          if kubectl get ing ${APP_NAME}-ui-alb -n ${K8S_NAMESPACE}; then
            echo "ui_ingress_exists=true" >> $GITHUB_ENV
          else
            echo "ui_ingress_exists=false" >> $GITHUB_ENV
          fi
        shell: bash
        continue-on-error: true

      - name: Check gateway ingress exists
        id: check_gateway_ingress
        run: |
          if kubectl get ing ${APP_NAME}-gateway-alb -n ${K8S_NAMESPACE}; then
            echo "gateway_ingress_exists=true" >> $GITHUB_ENV
          else
            echo "gateway_ingress_exists=false" >> $GITHUB_ENV
          fi
        shell: bash
        continue-on-error: true

      - name: Helm Uninstall
        if: env.release_exists == 'true'
        run: |
          helm uninstall ${APP_NAME} --namespace ${K8S_NAMESPACE}
        shell: bash

      - name: Patch and delete ingress for UI and Gateway
        if: env.ui_ingress_exists == 'true' || env.gateway_ingress_exists == 'true'
        run: |
          if [ "${{ env.ui_ingress_exists }}" == "true" ]; then
            kubectl patch ing ${APP_NAME}-ui-alb -n ${K8S_NAMESPACE} --type='merge' -p '{"metadata": {"finalizers": []}}'
          fi
          if [ "${{ env.gateway_ingress_exists }}" == "true" ]; then
            kubectl patch ing ${APP_NAME}-gateway-alb -n ${K8S_NAMESPACE} --type='merge' -p '{"metadata": {"finalizers": []}}'
          fi
          kubectl get ing -l release=${APP_NAME} --namespace ${K8S_NAMESPACE}
        shell: bash