name: Variables and Secrets

on: push

env:
    CONTAINER_REGISTRY: docker.io

jobs:
    docker:
        runs-on: ubuntu-latest
        steps:
        -  name: docker build
           run: echo docker build -t $CONTAINER_REGISTRY/${{ vars.USERNAME }}:latest

        -  name: docker login
           run: echo docker login $USERNAME -p ${{ secrets.PASSWORD }}
        
        -  name: docker publish
           run: docker push $CONTAINER_REGISTRY/${{ vars.USERNAME }}:latest