name: Variables and Secrets

on: push

env:
    CONTAINER_REGISTRY: docker.io

jobs:
    docker:
        runs-on: ubuntu-latest
        steps:
        -  name: docker build
           run: echo docker build -t $CONTAINER_REGISTRY/${{ vars.DOCKER_USERNAME }}:latest

        -  name: docker login
           run: echo docker login ${{ vars.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
        
        -  name: docker publish
           run: echo docker push $CONTAINER_REGISTRY/${{ vars.DOCKER_USERNAME }}:latest