name: Variables and Secrets

on: push

env:
    CONTAINER_REGISTRY: docker.io
    USERNAME: abc
    PASSWORD: 123

jobs:
    Docker_Login:
        runs-on: ubuntu:latest
        steps:
        -  name: Docker Login
           run: echo docker login $USERNAME -p $PASSWORD
    
    Docker_Build_Push:
        runs-on: ubuntu:latest
        steps:
            - name: Docker Build and Push
              run: |
                echo docker build -t $CONTAINER_REGISTRY/$USERNAME:latest
                echo docker push $CONTAINER_REGISTRY/$USERNAME:latest