name: Simple Docker Check and Conditional Command
run-name: Docker Check and Conditional Command

on: push

jobs:
  check-docker-and-file:
    runs-on: ubuntu-latest
    steps:
      - name: Check Docker version
        run: |
          docker --version
        shell: bash

      - name: Create a file
        run: |
          echo "This is a test file" > testfile.txt
        shell: bash

      - name: Conditional Command
        if: success() && (steps.create_file.outputs.exists == 'true')
        run: |
          echo "File exists, running the next command..."
          # Add your next command here
        shell: bash
