name: Conditional Steps Based on Command Success
run-name: Conditional Steps

on: push

jobs:
  conditional-steps:
    runs-on: ubuntu-latest
    steps:
      - name: Check Docker version
        id: check_docker
        run: |
          docker --versio
        shell: bash

      - name: Conditional Command
        if: success() && steps.check_docker.conclusion == 'success'
        run: |
          echo "Docker is installed, running the next command..."
          # Add your next command here
        shell: bash

      - name: Fallback Command
        if: failure()
        run: |
          echo "Docker is not installed, skipping the next command."
        shell: bash
